version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: point-checker-db
    environment:
      POSTGRES_DB: point_checker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Stepan2005
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - point-checker-network

  backend:
    build: 
      context: ./web_server
      dockerfile: Dockerfile
    container_name: point-checker-backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/point_checker
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Stepan2005
    ports:
      - "8080:8080"
    networks:
      - point-checker-network

  frontend:
    build:
      context: ./point-checker-frontend
      dockerfile: Dockerfile
    container_name: point-checker-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - point-checker-network

networks:
  point-checker-network:
    driver: bridge

volumes:
  postgres_data:
