spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/point_checker
    username: postgres
    password: Stepan2005
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: QWx3YXlzU2VjdXJlQmFzZTY0RW5jb2RlZAiuH2uiG5gdR4d
  expiration: 86400000

server:
  port: 8080
  servlet:
    context-path: /api